"""add url to category

Revision ID: 278b6ebb6e3f
Revises: 72a285a9f327
Create Date: 2026-06-23 18:37:48.256221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278b6ebb6e3f'
down_revision: Union[str, Sequence[str], None] = '72a285a9f327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'url')
    # ### end Alembic commands ###
